version: '3.7'

services:
    sample:
        container_name: react-todo
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
